### ISSUE TITLE
Pehkui and Size Entity Attributes are incompatible with each other.

### ISSUE THREAD

**Issue by sschr15** [MoriyaShiine/size-entity-attributes#1]
[(Posted in the Pehkui repo as well)](https://github.com/Virtuoel/Pehkui/issues/11)

Both Pehkui and Size Entity Attributes require mixing into `HorseBaseEntity` to modify a passenger's offsets. Both mods require it for the same reason, but since they both use `@ModifyConstant` with the same priority, they force only one of the two mods to succeed, which causes problems.

I will submit a PR soon to disable this mod's Mixin for `HorseBaseEntity` if it detects the other mod, and I will create a small bridge mod to sit between the two to provide compatibility.

**Comment by MoriyaShiine** [comment]
This mod is discontinued due to Pehkui existing, please use that instead.
