### ISSUE TITLE
Creepers and Wither Skeletons do not visiby resize.

### ISSUE THREAD

**Issue by ghost** [MoriyaShiine/size-entity-attributes#2]
**I am using:**
Fabric-Loader: 0.8.9+build203
Fabric-API: 0.17.0+build.386
SizeEntityAttributes: 1.16-3 (discovered on initially), also tested: 1.16-r2

**What happened:**
My mod spawns more of the same type of mob, at 75% of the height and width of the original mob. This works well for the majority of mobs I have tested. However, I have found that Wither Skeletons and Creepers only resize their hitbox, but not their physical appearance.

**What I mean: (regular skeletons included to show that other mobs work fine)**
![2020-08-15_20 22 38](https://user-images.githubusercontent.com/60057773/90310509-56c17080-df35-11ea-80a8-3f41a5322005.png)
![2020-08-15_20 24 20](https://user-images.githubusercontent.com/60057773/90310510-588b3400-df35-11ea-9ffe-5f4d34d35d93.png)

**Errors/Stacktraces:**
None

**Sample from my code:**
```javaEntity allSlime = entity.getType().create(entity.world);
entity.world.spawnEntity(allSlime);
LivingEntity ent = (LivingEntity) allSlime;

double width = entity.getAttributeInstance(SizeEntityAttributes.WIDTH_MULTIPLIER).getValue();
double height = entity.getAttributeInstance(SizeEntityAttributes.HEIGHT_MULTIPLIER).getValue();

ent.getAttributeInstance(SizeEntityAttributes.HEIGHT_MULTIPLIER).setBaseValue((height * 0.75));
ent.getAttributeInstance(SizeEntityAttributes.WIDTH_MULTIPLIER).setBaseValue((width * 0.75));```

**Comment by MoriyaShiine** [comment]
This mod is discontinued due to Pehkui existing, please use that instead.
